apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-tomcat-deployment
  labels:
    app: my-tomcat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-tomcat
  template:
    metadata:
      labels:
        app: my-tomcat
    spec:
      containers:
      - name: tomcat
        image: mikelogovi/my-tomcat-app
        ports:
        - containerPort: 8085
